# Copyright (c) 2016 Akuli, Chisight

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""This is a Paste ofCode file for QasteTray.

Thanks to Chisight <https://github.com/Chisight/> for making the
original pasting script. His version is available in his ghostbinit
Github repository. This is my (Akuli's) version of it.

The API documentation is here:
  https://ghostbin.com/paste/p3qcy
"""

import requests
from qastetray import USER_AGENT

name = 'Ghostbin'
url = 'https://ghostbin.com/'
expiry_days = [1, 7, 15]
syntax_default = 'Plain Text'
syntax_choices = {
    # This was generated with scripts/syntax_getters/ghostbin.py in the
    # QasteTray source package.
    "EBNF": "ebnf",
    "ANSI": "ansi",
    "Docker": "docker",
    "PyPy Log": "pypylog",
    "eC": "ec",
    "Coq": "coq",
    "Hy": "hylang",
    "Ragel": "ragel",
    "Ceylon": "ceylon",
    "HTML+Cheetah": "html+cheetah",
    "Go": "go",
    "Xtend": "xtend",
    "Modelica": "modelica",
    "JavaScript+Myghty": "js+myghty",
    "Coldfusion CFC": "cfc",
    "Tcsh": "tcsh",
    "Hxml": "haxeml",
    "Objective-C++": "objective-c++",
    "Io": "io",
    "XQuery": "xquery",
    "Python 3": "python3",
    "ca65": "ca65",
    "Logos + Objective-C": "logos",
    "Cython": "cython",
    "Brainfuck": "brainfuck",
    "FoxPro": "foxpro",
    "Sass": "sass",
    "Hybris": "hybris",
    "Nix": "nixos",
    "AutoIt": "autoit",
    "Inform 7": "inform7",
    "Cirru": "cirru",
    "NASM": "nasm",
    "Cheetah": "cheetah",
    "Fortran": "fortran",
    "nesC": "nesc",
    "Pike": "pike",
    "liquid": "liquid",
    "Kal": "kal",
    "BUGS": "bugs",
    "ActionScript": "as",
    "Elixir": "elixir",
    "IDL": "idl",
    "COBOL": "cobol",
    "JavaScript+Cheetah": "js+cheetah",
    "XML+Lasso": "xml+lasso",
    "Groff": "groff",
    "CSS+PHP": "css+php",
    "VGL": "vgl",
    "Monkey": "monkey",
    "SquidConf": "squidconf",
    "Gosu": "gosu",
    "Agda": "agda",
    "Clay": "clay",
    "Cypher": "cypher",
    "Elixir iex session": "iex",
    "ERB": "erb",
    "AppleScript": "applescript",
    "XML+Django/Jinja": "xml+django",
    "Modula-2": "modula2",
    "Literate Haskell": "lhs",
    "ANTLR With Ruby Target": "antlr-ruby",
    "objdump-nasm": "objdump-nasm",
    "Redcode": "redcode",
    "MuPAD": "mupad",
    "Jasmin": "jasmin",
    "ANTLR With Java Target": "antlr-java",
    "SPARQL": "sparql",
    "Literate Agda": "lagda",
    "AspectJ": "aspectj",
    "Matlab session": "matlabsession",
    "Chapel": "chapel",
    "Genshi": "genshi",
    "Kconfig": "kconfig",
    "HTML+Myghty": "html+myghty",
    "Fancy": "fancy",
    "Ragel in D Host": "ragel-d",
    "BlitzMax": "blitzmax",
    "Python Traceback": "pytb",
    "Alloy": "alloy",
    "Red": "red",
    "CSS+Myghty": "css+myghty",
    "reg": "registry",
    "Erlang erl session": "erl",
    "XML+Myghty": "xml+myghty",
    "MoonScript": "moon",
    "ANTLR With ActionScript Target": "antlr-as",
    "C#": "csharp",
    "JSON": "json",
    "HTML+Django/Jinja": "html+django",
    "Vala": "vala",
    "Swift": "swift",
    "Coldfusion HTML": "cfm",
    "ABAP": "abap",
    "NumPy": "numpy",
    "CSS+Ruby": "css+erb",
    "Ragel in C Host": "ragel-c",
    "XML+Mako": "xml+mako",
    "JAGS": "jags",
    "Python console session": "pycon",
    "JavaScript+Django/Jinja": "js+django",
    "Smalltalk": "smalltalk",
    "HTML+Velocity": "html+velocity",
    "YAML": "yaml",
    "CSS": "css",
    "Boo": "boo",
    "CSS+Django/Jinja": "css+django",
    "d-objdump": "d-objdump",
    "XML+Velocity": "xml+velocity",
    "PostgreSQL console (psql)": "psql",
    "Felix": "felix",
    "RConsole": "rconsole",
    "Tea": "tea",
    "Django/Jinja": "django",
    "CSS+Lasso": "css+lasso",
    "NewLisp": "newlisp",
    "Eiffel": "eiffel",
    "MoinMoin/Trac Wiki markup": "trac-wiki",
    "COBOLFree": "cobolfree",
    "Gosu Template": "gst",
    "PHP": "php",
    "OpenEdge ABL": "openedge",
    "Ruby": "rb",
    "HTML+Handlebars": "html+handlebars",
    "Rexx": "rexx",
    "ANTLR With Perl Target": "antlr-perl",
    "Prolog": "prolog",
    "Shell Session": "shell-session",
    "Ragel in Ruby Host": "ragel-ruby",
    "Mask": "mask",
    "Lasso": "lasso",
    "python": "python",
    "Bro": "bro",
    "Literate Idris": "lidr",
    "Fantom": "fan",
    "GAS": "gas",
    "XML+PHP": "xml+php",
    "Golo": "golo",
    "HTML+Evoque": "html+evoque",
    "Scilab": "scilab",
    "PostScript": "postscript",
    "Octave": "octave",
    "JavaScript+Ruby": "js+erb",
    "JavaScript+Genshi Text": "js+genshitext",
    "c-objdump": "c-objdump",
    "Plain Text": "text",
    "Scheme": "scheme",
    "MXML": "mxml",
    "ANTLR With Python Target": "antlr-python",
    "CFEngine3": "cfengine3",
    "JavaScript": "js",
    "JavaScript+Mako": "js+mako",
    "APL": "apl",
    "XML+Evoque": "xml+evoque",
    "Ioke": "ioke",
    "Makefile": "make",
    "Java": "java",
    "Nimrod": "nimrod",
    "Velocity": "velocity",
    "ANTLR With ObjectiveC Target": "antlr-objc",
    "Idris": "idris",
    "Pig": "pig",
    "Debian Control file": "control",
    "reStructuredText": "rst",
    "FSharp": "fsharp",
    "Mscgen": "mscgen",
    "CMake": "cmake",
    "Batchfile": "bat",
    "cfstatement": "cfs",
    "Nemerle": "nemerle",
    "ANTLR With CPP Target": "antlr-cpp",
    "Rust": "rust",
    "Racket": "racket",
    "RobotFramework": "robotframework",
    "Myghty": "myghty",
    "MySQL": "mysql",
    "CSS+Genshi Text": "css+genshitext",
    "ApacheConf": "apacheconf",
    "CUDA": "cuda",
    "Factor": "factor",
    "GAP": "gap",
    "Scala": "scala",
    "SCSS": "scss",
    "XML": "xml",
    "Ruby irb session": "rbcon",
    "LiveScript": "live-script",
    "TypeScript": "ts",
    "C": "c",
    "Gherkin": "cucumber",
    "Standard ML": "sml",
    "HTTP": "http",
    "Ada": "ada",
    "GoodData-CL": "gooddata-cl",
    "Properties": "properties",
    "XML+Smarty": "xml+smarty",
    "QML": "qml",
    "RQL": "rql",
    "Koka": "koka",
    "Lua": "lua",
    "Gnuplot": "gnuplot",
    "Haskell": "haskell",
    "MiniD": "minid",
    "CSS+Smarty": "css+smarty",
    "XML+Ruby": "xml+erb",
    "ANTLR": "antlr",
    "Ragel in Java Host": "ragel-java",
    "Julia console": "jlcon",
    "Bash Session": "console",
    "Haml": "haml",
    "Jade": "jade",
    "Treetop": "treetop",
    "Java Server Page": "jsp",
    "MOOCode": "moocode",
    "JavaScript+Lasso": "js+lasso",
    "R": "splus",
    "BlitzBasic": "blitzbasic",
    "Mathematica": "mathematica",
    "ActionScript 3": "as3",
    "INI": "ini",
    "verilog": "verilog",
    "OCaml": "ocaml",
    "PowerShell": "powershell",
    "YAML+Jinja": "yaml+jinja",
    "Handlebars": "handlebars",
    "MQL": "mql",
    "Ragel in CPP Host": "ragel-cpp",
    "sqlite3con": "sqlite3",
    "Clojure": "clojure",
    "MAQL": "maql",
    "Inform 6 template": "i6t",
    "Igor": "igor",
    "Dart": "dart",
    "Awk": "awk",
    "DylanLID": "dylan-lid",
    "Duel": "duel",
    "ANTLR With C# Target": "antlr-csharp",
    "Logtalk": "logtalk",
    "ClojureScript": "clojurescript",
    "JavaScript+Smarty": "js+smarty",
    "QBasic": "qbasic",
    "VCTreeStatus": "vctreestatus",
    "cpp-objdump": "cpp-objdump",
    "Snobol": "snobol",
    "C++": "cpp",
    "Cryptol": "cryptol",
    "Perl": "perl",
    "Base Makefile": "basemake",
    "D": "d",
    "Limbo": "limbo",
    "Groovy": "groovy",
    "HTML+Genshi": "html+genshi",
    "Smarty": "smarty",
    "LSL": "lsl",
    "Mason": "mason",
    "HTML+Smarty": "html+smarty",
    "TeX": "tex",
    "autohotkey": "ahk",
    "Darcs Patch": "dpatch",
    "Common Lisp": "common-lisp",
    "Stan": "stan",
    "Befunge": "befunge",
    "Mako": "mako",
    "Rd": "rd",
    "aspx-cs": "aspx-cs",
    "BBCode": "bbcode",
    "LLVM": "llvm",
    "Bash": "bash",
    "iOS System Log": "iphonesyslog",
    "CoffeeScript": "coffee-script",
    "DTD": "dtd",
    "Haxe": "hx",
    "VB.net": "vb.net",
    "UrbiScript": "urbiscript",
    "Zephir": "zephir",
    "Inform 6": "inform6",
    "Croc": "croc",
    "ChaiScript": "chai",
    "Dylan": "dylan",
    "Newspeak": "newspeak",
    "vhdl": "vhdl",
    "POVRay": "pov",
    "Scalate Server Page": "ssp",
    "ECL": "ecl",
    "VimL": "vim",
    "HTML+Mako": "html+mako",
    "Opa": "opa",
    "GLSL": "glsl",
    "Scaml": "scaml",
    "Matlab": "matlab",
    "Python 3.0 Traceback": "py3tb",
    "IRC Log": "irc",
    "AmbientTalk": "at",
    "Todotxt": "todotxt",
    "RHTML": "rhtml",
    "Julia": "julia",
    "Objective-J": "objective-j",
    "Pawn": "pawn",
    "XSLT": "xslt",
    "Ooc": "ooc",
    "Gettext Catalog": "pot",
    "Tcl": "tcl",
    "Smali": "smali",
    "Genshi Text": "genshitext",
    "HTML+PHP": "html+php",
    "Kotlin": "kotlin",
    "PL/pgSQL": "plpgsql",
    "SWIG": "swig",
    "HTML+Lasso": "html+lasso",
    "CBM BASIC V2": "cbmbas",
    "XML+Cheetah": "xml+cheetah",
    "Erlang": "erlang",
    "Puppet": "puppet",
    "Slim": "slim",
    "Nginx configuration file": "nginx",
    "Protocol Buffer": "protobuf",
    "Perl6": "perl6",
    "Lighttpd configuration file": "lighty",
    "Literate Cryptol": "lcry",
    "Objective-C": "objective-c",
    "JavaScript+PHP": "js+php",
    "Debian Sourcelist": "sourceslist",
    "Pan": "pan",
    "RPMSpec": "spec",
    "Dylan session": "dylan-console",
    "PostgreSQL SQL dialect": "postgresql",
    "SourcePawn": "sp",
    "systemverilog": "systemverilog",
    "Delphi": "delphi",
    "SQL": "sql",
    "CSS+Mako": "css+mako",
    "RSL": "rsl",
    "Asymptote": "asy",
    "REBOL": "rebol",
    "NSIS": "nsis",
    "Markdown": "markdown",
    "Embedded Ragel": "ragel-em",
    "aspx-vb": "aspx-vb",
    "HTML": "html",
    "Evoque": "evoque",
    "Diff": "diff",
    "objdump": "objdump",
    "Ragel in Objective C Host": "ragel-objc",
    "dg": "dg"
}

paste_args = ['content', 'expiry', 'syntax', 'title']


def paste(content, expiry, syntax, title):
    """Make a paste to dpaste.com."""
    response = requests.post(
        'https://ghostbin.com/paste/new',
        data={'text': content},
        params={
            'expire': str(expiry) + 'd',
            'lang': syntax,
            'title': title,
        },
        headers={'User-Agent': USER_AGENT},
    )
    response.raise_for_status()
    return response.url
